.TH PSMEM 1 psmem\-1.0
.SH NAME
psmem \- report memory usage of running programs
.SH SYNOPSIS
.B psmem
[ ]
.SH DESCRIPTION
.B psmem
is a utilty to report the memory usage of running
programs. 

Running 
.B psmem
with superuser permissions will provide more accurate results.
.SH OPTIONS
.B psmem
does not take any options, running it with any will output a usage message and exit.
.SH AUTHOR
jason <https://github.com/jastintime>
.SH BUGS
Knows bugs are listed at
.I https://github.com/jastintime/psmem/issues
.SH SEE ALSO
.BR ps_mem (1)


